# vim: set expandtab shiftwidth=2 :

image: debian:unstable

before_script:
  - apt-get update
  - apt-get install -y clang-tidy clang-format g++ meson git

build:
  script:
    - meson setup build
    - meson compile -C build
  artifacts:
    paths:
      - "build/src/translate"
  cache:
    paths:
      - "build"
