#include "generator/x86_64/helper/rv64_syscalls.h"

namespace helper {

#include "generator/syscall_ids.h"

const SyscallInfo rv64_syscall_table[static_cast<size_t>(RISCV_SYSCALL_ID::SYSCALL_ID_MAX) + 1]{
    // RISCV_IO_SETUP
    {SyscallAction::unimplemented, 2, AMD64_SYSCALL_ID::SYSCALL_ID_INVALID},
    // RISCV_IO_DESTROY
    {SyscallAction::unimplemented, 1, AMD64_SYSCALL_ID::SYSCALL_ID_INVALID},
    // RISCV_IO_SUBMIT
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::SYSCALL_ID_INVALID},
    // RISCV_IO_CANCEL
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::SYSCALL_ID_INVALID},
    // RISCV_IO_GET_EVENTS
    {SyscallAction::unimplemented, 5, AMD64_SYSCALL_ID::SYSCALL_ID_INVALID},
    // RISCV_SETXATTR = 5,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::SETXATTR},
    // RISCV_LSETXATTR = 6,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::LSETXATTR},
    // RISCV_FSETXATTR = 7,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::FSETXATTR},
    // RISCV_GETXATTR = 8,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::GETXATTR},
    // RISCV_LGETXATTR = 9,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::LGETXATTR},
    // RISCV_FGETXATTR = 10,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::FGETXATTR},
    // RISCV_LISTXATTR = 11,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::LISTXATTR},
    // RISCV_LLISTXATTR = 12,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::LLISTXATTR},
    // RISCV_FLISTXATTR = 13,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::FLISTXATTR},
    // RISCV_REMOVEXATTR = 14,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::REMOVEXATTR},
    // RISCV_LREMOVEXATTR = 15,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::LREMOVEXATTR},
    // RISCV_FREMOVEXATTR = 16,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::FREMOVEXATTR},
    // RISCV_GETCWD = 17,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::GETCWD},
    // RISCV_LOOKUP_DCOOKIE = 18,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::LOOKUP_DCOOKIE},
    // RISCV_EVENTFD2 = 19,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::EVENTFD2},
    // RISCV_EPOLL_CREATE1 = 20,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::EPOLL_CREATE1},
    // RISCV_EPOLL_CTL = 21,
    {SyscallAction::handle, 4, AMD64_SYSCALL_ID::EPOLL_CTL},
    // RISCV_EPOLL_PWAIT = 22,
    {SyscallAction::handle, 6, AMD64_SYSCALL_ID::EPOLL_PWAIT},
    // RISCV_DUP = 23,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::DUP},
    // RISCV_DUP3 = 24,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::DUP3},
    // RISCV_FCNTL = 25,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::FCNTL},
    // RISCV_INOTIFY_INIT1 = 26,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::INOTIFY_INIT1},
    // RISCV_INOTIFY_ADD_WATCH = 27,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::INOTIFY_ADD_WATCH},
    // RISCV_INOTIFY_RM_WATCH = 28,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::INOTIFY_RM_WATCH},
    // RISCV_IOCTL = 29,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::IOCTL},
    // RISCV_IOPRIO_SET = 30,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::IOPRIO_SET},
    // RISCV_IOPRIO_GET = 31,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::IOPRIO_GET},
    // RISCV_FLOCK = 32,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::FLOCK},
    // RISCV_MKNODAT = 33,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::MKNODAT},
    // RISCV_MKDIRAT = 34,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::MKDIRAT},
    // RISCV_UNLINKAT = 35,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::UNLINKAT},
    // RISCV_SYMLINKAT = 36,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SYMLINKAT},
    // RISCV_LINKAT = 37,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::LINKAT},
    // // 38 is skipped
    {SyscallAction::unimplemented, 0, AMD64_SYSCALL_ID::SYSCALL_ID_INVALID},
    // RISCV_UMOUNT2 = 39,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::UMOUNT2},
    // RISCV_MOUNT = 40,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::MOUNT},
    // RISCV_PIVOT_ROOT = 41,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::PIVOT_ROOT},
    // // nfsservectl, doesn't exist since linux 3.1
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::SYSCALL_ID_INVALID},
    // RISCV_STATFS = 43,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::STATFS},
    // RISCV_FSTATFS = 44,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::FSTATFS},
    // RISCV_TRUNCATE = 45,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::TRUNCATE},
    // RISCV_FTRUNCATE = 46,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::FTRUNCATE},
    // RISCV_FALLOCATE = 47,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::FALLOCATE},
    // RISCV_FACCESSAT = 48,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::FACCESSAT},
    // RISCV_CHDIR = 49,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::CHDIR},
    // RISCV_FCHDIR = 50,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::FCHDIR},
    // RISCV_CHROOT = 51,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::CHROOT},
    // RISCV_FCHMOD = 52,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::FCHMOD},
    // RISCV_FCHMODAT = 53,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::FCHMODAT},
    // RISCV_FCHOWNAT = 54,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::FCHOWNAT},
    // RISCV_FCHOWN = 55,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::FCHOWN},
    // RISCV_OPENAT = 56,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::OPENAT},
    // RISCV_CLOSE = 57,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::CLOSE},
    // RISCV_VHANGUP = 58,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::VHANGUP},
    // RISCV_PIPE2 = 59,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::PIPE2},
    // RISCV_QUOTACTL = 60,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::QUOTACTL},
    // RISCV_GETDENTS64 = 61,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::GETDENTS64},
    // RISCV_LSEEK = 62,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::LSEEK},
    // RISCV_READ = 63,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::READ},
    // RISCV_WRITE = 64,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::WRITE},
    // RISCV_READV = 65,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::READV},
    // RISCV_WRITEV = 66,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::WRITEV},
    // RISCV_PREAD64 = 67,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::PREAD64},
    // RISCV_PWRITE64 = 68,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::PWRITE64},
    // RISCV_PREADV = 69, TODO: the fourth arg is one 64bit but is split into high and low part on x64, check if its the same on riscv
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::PREADV},
    // RISCV_PWRITEV = 70, same as above
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::PWRITEV},
    // RISCV_SENDFILE = 71,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::SENDFILE},
    // RISCV_PSELECT6 = 72,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::PSELECT6},
    // RISCV_PPOLL = 73,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::PPOLL},
    // RISCV_SIGNALFD4 = 74,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::SIGNALFD4},
    // RISCV_VMSPLICE = 75,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::VMSPLICE},
    // RISCV_SPLICE = 76,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::SPLICE},
    // RISCV_TEE = 77,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::TEE},
    // RISCV_READ_LINK_AT = 78,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::READ_LINK_AT},
    // RISCV_FSTATAT = 79,
    {SyscallAction::handle, 4, AMD64_SYSCALL_ID::NEWFSTATAT},
    // RISCV_FSTAT = 80,
    {SyscallAction::handle, 2, AMD64_SYSCALL_ID::FSTAT},
    // RISCV_SYNC = 81,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::SYNC},
    // RISCV_FSYNC = 82,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::FSYNC},
    // RISCV_FDATASYNC = 83,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::FDATASYNC},
    // RISCV_SYNC_FILE_RANGE = 84,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::SYNC_FILE_RANGE},
    // RISCV_TIMERFD_CREATE = 85,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::TIMERFD_CREATE},
    // RISCV_TIMERFD_SETTIME = 86,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::TIMERFD_SETTIME},
    // RISCV_TIMERFD_GETTIME = 87,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::TIMERFD_GETTIME},
    // RISCV_UTIME_NS_AT = 88,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::UTIME_NS_AT},
    // RISCV_ACCT = 89,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::ACCT},
    // RISCV_CAPGET = 90,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::CAPGET},
    // RISCV_CAPSET = 91,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::CAPSET},
    // RISCV_PERSONALITY = 92,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::PERSONALITY},
    // RISCV_EXIT = 93,
    {SyscallAction::handle, 1, AMD64_SYSCALL_ID::EXIT},
    // RISCV_EXIT_GROUP = 94,
    {SyscallAction::handle, 1, AMD64_SYSCALL_ID::EXIT_GROUP},
    // RISCV_WAITID = 95,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::WAITID},
    // RISCV_SET_TID_ADDR = 96,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SET_TID_ADDR},
    // RISCV_UNSHARE = 97,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::UNSHARE},
    // RISCV_FUTEX = 98,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::FUTEX},
    // RISCV_SET_ROBUST_LIST = 99,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SET_ROBUST_LIST},
    // RISCV_GET_ROBUST_LIST = 100,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::GET_ROBUST_LIST},
    // RISCV_NANOSLEEP = 101,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::NANOSLEEP},
    // RISCV_GETITIMER = 102,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::GETITIMER},
    // RISCV_SETITIMER = 103,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SETITIMER},
    // RISCV_KEXEC_LOAD = 104,
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::KEXEC_LOAD},
    // RISCV_INIT_MODULE = 105,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::INIT_MODULE},
    // RISCV_DELETE_MODULE = 106,
    {SyscallAction::unimplemented, 2, AMD64_SYSCALL_ID::DELETE_MODULE},
    // RISCV_TIMER_CREATE = 107, timer functions need signal support
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::TIMER_CREATE},
    // RISCV_TIMER_GETTIME = 108,
    {SyscallAction::unimplemented, 2, AMD64_SYSCALL_ID::TIMER_GETTIME},
    // RISCV_TIMER_GETOVERRUN = 109,
    {SyscallAction::unimplemented, 1, AMD64_SYSCALL_ID::TIMER_GETOVERRUN},
    // RISCV_TIMER_SETTIME = 110,
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::TIMER_SETTIME},
    // RISCV_TIMER_DELETE = 111,
    {SyscallAction::unimplemented, 1, AMD64_SYSCALL_ID::TIMER_DELETE},
    // RISCV_CLOCK_SETTIME = 112,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::CLOCK_SETTIME},
    // RISCV_CLOCK_GET_TIME = 113,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::CLOCK_GET_TIME},
    // RISCV_CLOCK_GETRES = 114,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::CLOCK_GETRES},
    // RISCV_CLOCK_NANOSLEEP = 115,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::CLOCK_NANOSLEEP},
    // RISCV_SYSLOG = 116,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SYSLOG},
    // RISCV_PTRACE = 117, deals with arch-specific data
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::PTRACE},
    // RISCV_SCHED_SETPARAM = 118, riscv struct is bigger with padding bytes
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SCHED_SETPARAM},
    // RISCV_SCHED_SETSCHEDULER = 119,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SCHED_SETSCHEDULER},
    // RISCV_SCHED_GETSCHEDULER = 120,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SCHED_GETSCHEDULER},
    // RISCV_SCHED_GETPARAM = 121,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SCHED_GETPARAM},
    // RISCV_SCHED_SETAFFINITY = 122,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SCHED_SETAFFINITY},
    // RISCV_SCHED_GETAFFINITY = 123,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SCHED_GETAFFINITY},
    // RISCV_SCHED_YIELD = 124,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::SCHED_YIELD},
    // RISCV_SCHED_GET_PRIORITY_MAX = 125,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SCHED_GET_PRIORITY_MAX},
    // RISCV_SCHED_GET_PRIORITY_MIN = 126,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SCHED_GET_PRIORITY_MIN},
    // RISCV_SCHED_RR_GET_INTERVAL = 127,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SCHED_RR_GET_INTERVAL},
    // RISCV_RESTART_SYSCALL = 128,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::RESTART_SYSCALL},
    // RISCV_KILL = 129,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::KILL},
    // RISCV_TKILL = 130,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::TKILL},
    // RISCV_TGKILL = 131,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::TGKILL},
    // RISCV_SIGALTSTACK = 132,
    {SyscallAction::succeed, 2, AMD64_SYSCALL_ID::SIGALTSTACK},
    // RISCV_RT_SIGSUSPEND = 133, cant emulate in a meaningful way
    {SyscallAction::unimplemented, 2, AMD64_SYSCALL_ID::RT_SIGSUSPEND},
    // RISCV_RT_SIGACTION = 134,
    {SyscallAction::succeed, 4, AMD64_SYSCALL_ID::RT_SIGACTION},
    // RISCV_RT_SIGPROCMASK = 135,
    {SyscallAction::succeed, 4, AMD64_SYSCALL_ID::RT_SIGPROCMASK},
    // RISCV_RT_SIGPENDING = 136,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::RT_SIGPENDING},
    // RISCV_RT_SIGTIMEDWAIT = 137,
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::RT_SIGTIMEDWAIT},
    // RISCV_RT_SIGQUEUEINFO = 138,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::RT_SIGQUEUEINFO},
    // RISCV_RT_SIGRETURN = 139,
    {SyscallAction::unimplemented, 0, AMD64_SYSCALL_ID::RT_SIGRETURN},
    // RISCV_SETPRIORITY = 140,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SETPRIORITY},
    // RISCV_GETPRIORITY = 141,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::GETPRIORITY},
    // RISCV_REBOOT = 142,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::REBOOT},
    // RISCV_SETREGID = 143,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SETREGID},
    // RISCV_SETGID = 144,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SETGID},
    // RISCV_SETREUID = 145,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SETREUID},
    // RISCV_SETUID = 146,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SETUID},
    // RISCV_SETRESUID = 147,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SETRESUID},
    // RISCV_GETRESUID = 148,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::GETRESUID},
    // RISCV_SETRESGID = 149,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SETRESGID},
    // RISCV_GETRESGID = 150,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::GETRESGID},
    // RISCV_SETFSUID = 151,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SETFSUID},
    // RISCV_SETFSGID = 152,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SETFSGID},
    // RISCV_TIMES = 153,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::TIMES},
    // RISCV_SETPGID = 154,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SETPGID},
    // RISCV_GETPGID = 155,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::GETPGID},
    // RISCV_GETSID = 156,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::GETSID},
    // RISCV_SETSID = 157,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::SETSID},
    // RISCV_GETGROUPS = 158,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::GETGROUPS},
    // RISCV_SETGROUPS = 159,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SETGROUPS},
    // RISCV_UNAME = 160,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::UNAME},
    // RISCV_SETHOSTNAME = 161,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SETHOSTNAME},
    // RISCV_SETDOMAINNAME = 162,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SETDOMAINNAME},
    // RISCV_GETRLIMIT = 163,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::GETRLIMIT},
    // RISCV_SETRLIMIT,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SETRLIMIT},
    // RISCV_GETRUSAGE,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::GETRUSAGE},
    // RISCV_UMASK,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::UMASK},
    // RISCV_PRCTL,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::PRCTL},
    // RISCV_GETCPU, (third argument is internal cache)
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::GETCPU},
    // RISCV_GETTIMEOFDAY,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::GETTIMEOFDAY},
    // RISCV_SETTIMEOFDAY,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SETTIMEOFDAY},
    // RISCV_ADJTIMEEX,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::ADJTIMEX},
    // RISCV_GETPID,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::GETPID},
    // RISCV_GETPPID,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::GETPPID},
    // RISCV_GETUID,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::GETUID},
    // RISCV_GETEUID,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::GETEUID},
    // RISCV_GETGID,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::GETGID},
    // RISCV_GETEGID,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::GETEGID},
    // RISCV_GETTID,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::GETTID},
    // RISCV_SYSINFO,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SYSINFO},
    // RISCV_MQ_OPEN,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::MQ_OPEN},
    // RISCV_MQ_UNLINK,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::MQ_UNLINK},
    // RISCV_MQ_TIMEDSEND,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::MQ_TIMEDSEND},
    // RISCV_MQ_TIMEDRECEIVE,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::MQ_TIMEDRECEIVE},
    // RISCV_MQ_NOTIFY,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::MQ_NOTIFY},
    // RISCV_MQ_GETSETATTR,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::MQ_GETSETATTR},
    // RISCV_MSGGET,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::MSGGET},
    // RISCV_MSGCTL,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::MSGCTL},
    // RISCV_MSGRCV,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::MSGRCV},
    // RISCV_MSGSND,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::MSGSND},
    // RISCV_SEMGET,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SEMGET},
    // RISCV_SEMCTL,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::SEMCTL},
    // RISCV_SEMTIMEDOP,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::SEMTIMEDOP},
    // RISCV_SEMOP,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SEMOP},
    // RISCV_SHMGET,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SHMGET},
    // RISCV_SHMCTL,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SHMCTL},
    // RISCV_SHMAT,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SHMAT},
    // RISCV_SHMDT,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SHMDT},
    // RISCV_SOCKET, socket stuff structs need to be checked
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::SOCKET},
    // RISCV_SOCKETPAIR,
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::SOCKETPAIR},
    // RISCV_BIND,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::BIND},
    // RISCV_LISTEN,
    {SyscallAction::unimplemented, 2, AMD64_SYSCALL_ID::LISTEN},
    // RISCV_ACCEPT,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::ACCEPT},
    // RISCV_CONNECT,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::CONNECT},
    // RISCV_GETSOCKETNAME,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::GETSOCKETNAME},
    // RISCV_GETPEERNAME,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::GETPEERNAME},
    // RISCV_SENDTO,
    {SyscallAction::unimplemented, 6, AMD64_SYSCALL_ID::SENDTO},
    // RISCV_RECVFROM,
    {SyscallAction::unimplemented, 6, AMD64_SYSCALL_ID::RECVFROM},
    // RISCV_SETSOCKOPT,
    {SyscallAction::unimplemented, 5, AMD64_SYSCALL_ID::SETSOCKOPT},
    // RISCV_GETSOCKOPT,
    {SyscallAction::unimplemented, 5, AMD64_SYSCALL_ID::GET_SOCKOPT},
    // RISCV_SHUTDOWN,
    {SyscallAction::unimplemented, 2, AMD64_SYSCALL_ID::SHUTDOWN},
    // RISCV_SENDMSG,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::SENDMSG},
    // RISCV_RECVMSG,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::RECVMSG},
    // RISCV_READAHEAD,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::READAHEAD},
    // RISCV_BRK = 214,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::BRK},
    // RISCV_MUNMAP = 215,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::MUNMAP},
    // RISCV_MREMAP,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::MREMAP},
    // RISCV_ADD_KEY,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::ADD_KEY},
    // RISCV_REQUEST_KEY,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::REQUEST_KEY},
    // RISCV_KEYCTL,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::KEYCTL},
    // RISCV_CLONE,
    {SyscallAction::handle, 5, AMD64_SYSCALL_ID::CLONE},
    // RISCV_EXECVE,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::EXECVE},
    // RISCV_MMAP = 222,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::MMAP},
    // RISCV_FADVISE64,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::FADVISE64},
    // RISCV_SWAPON,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SWAPON},
    // RISCV_SWAPOFF,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SWAPOFF},
    // RISCV_MPROTECT = 226,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::MPROTECT},
    // RISCV_MSYNC,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::MSYNC},
    // RISCV_MLOCK,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::MLOCK},
    // RISCV_MUNLOCK,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::MUNLOCK},
    // RISCV_MLOCKALL,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::MLOCKALL},
    // RISCV_MUNLOCKALL,
    {SyscallAction::passthrough, 0, AMD64_SYSCALL_ID::MUNLOCKALL},
    // RISCV_MINCORE,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::MINCORE},
    // RISCV_MADVISE = 233,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::MADVISE},
    // RISCV_REMAP_FILE_PAGES,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::REMAP_FILE_PAGES},
    // RISCV_MBIND,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::MBIND},
    // RISCV_GET_MEMPOLICY,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::GET_MEMPOLICY},
    // RISCV_SET_MEMPOLICY,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SET_MEMPOLICY},
    // RISCV_MIGRATE_PAGES,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::MIGRATE_PAGES},
    // RISCV_MOVE_PAGES,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::MOVE_PAGES},
    // RISCV_RT_TGSIGQUEUEINFO,
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::RT_TGSIGQUEUEINFO},
    // RISCV_PERF_EVENT_OPEN,
    {SyscallAction::unimplemented, 5, AMD64_SYSCALL_ID::PERF_EVENT_OPEN},
    // RISCV_ACCEPT4,
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::ACCEPT4},
    // RISCV_RECVMMSG,
    {SyscallAction::unimplemented, 5, AMD64_SYSCALL_ID::RECVMMSG},
    // 15 skipped (architecture specific)
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    // RISCV_FLUSH_ICACHE,
    {SyscallAction::succeed, 3, AMD64_SYSCALL_ID::SYSCALL_ID_INVALID},
    // RISCV_WAIT4,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::WAIT4},
    // RISCV_PRLIMIT64,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::PRLIMIT64},
    // RISCV_FANOTIFY_INIT,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::FANOTIFY_INIT},
    // RISCV_FANOTIFY_MARK,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::FANOTIFY_MARK},
    // RISCV_NAME_TO_HANDLE_AT,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::NAME_TO_HANDLE_AT},
    // RISCV_OPEN_BY_HANDLE_AT,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::OPEN_BY_HANDLE_AT},
    // RISCV_CLOCK_ADJTIME,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::CLOCK_ADJTIME},
    // RISCV_SYNCFS,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::SYNCFS},
    // RISCV_SETNS,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::SETNS},
    // RISCV_SENDMMSG,
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::SENDMMSG},
    // RISCV_PROCESS_VM_READV,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::PROCESS_VM_READV},
    // RISCV_PROCESS_VM_WRITEV,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::PROCESS_VM_WRITEV},
    // RISCV_KCMP,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::KCMP},
    // RISCV_FINIT_MODULE,
    {SyscallAction::unimplemented, 3, AMD64_SYSCALL_ID::FINIT_MODULE},
    // RISCV_SCHED_SETATTR,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SCHED_SETATTR},
    // RISCV_SCHED_GETATTR,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::SCHED_GETATTR},
    // RISCV_RENAMEAT2,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::RENAMEAT2},
    // RISCV_SECCOMP, arch-specific stuff?
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::SECCOMP},
    // RISCV_GETRANDOM,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::GETRANDOM},
    // RISCV_MEMFDCREATE,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::MEMFD_CREATE},
    // RISCV_BPF,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::BPF},
    // RISCV_EXECVEAT,
    {SyscallAction::unimplemented, 5, AMD64_SYSCALL_ID::EXECVEAT},
    // RISCV_USERFAULTFD,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::USERFAULTFD},
    // RISCV_MEMBARRIER,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::MEMBARRIER},
    // RISCV_MLOCK2,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::MLOCK2},
    // RISCV_COPY_FILE_RANGE,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::COPY_FILE_RANGE},
    // RISCV_PREADV2,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::PREADV2},
    // RISCV_PWRITEV2,
    {SyscallAction::passthrough, 6, AMD64_SYSCALL_ID::PWRITEV2},
    // RISCV_PKEY_MPROTECT,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::PKEY_MPROTECT},
    // RISCV_PKEY_ALLOC,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::PKEY_ALLOC},
    // RISCV_PKEY_FREE,
    {SyscallAction::passthrough, 1, AMD64_SYSCALL_ID::PKEY_FREE},
    // RISCV_STATX,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::STATX},
    // RISCV_IO_PGETEVENTS,
    {SyscallAction::unimplemented, 6, AMD64_SYSCALL_ID::IO_PGETEVENTS},
    // RISCV_RSEQ,
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::RSEQ},
    // RISCV_KEXEC_FILE_LOAD = 294,
    {SyscallAction::unimplemented, 5, AMD64_SYSCALL_ID::KEXEC_FILE_LOAD},
    // 424 - 295 = 129 zero entries
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    // RISCV_PIDFD_SEND_SIGNAL = 424,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::PIDFD_SEND_SIGNAL},
    // RISCV_IO_URING_SETUP, not sure about the structs
    {SyscallAction::unimplemented, 2, AMD64_SYSCALL_ID::IO_URING_SETUP},
    // RISCV_IO_URING_ENTER,
    {SyscallAction::unimplemented, 6, AMD64_SYSCALL_ID::IO_URING_ENTER},
    // RISCV_IO_URING_REGISTER,
    {SyscallAction::unimplemented, 4, AMD64_SYSCALL_ID::IO_URING_REGISTER},
    // RISCV_OPEN_TREE,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::OPEN_TREE},
    // RISCV_MOVE_MOUNT,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::MOVE_MOUNT},
    // RISCV_FSOPEN,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::FSOPEN},
    // RISCV_FSCONFIG,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::FSCONFIG},
    // RISCV_FSMOUNT,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::FSMOUNT},
    // RISCV_FSPICK,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::FSPICK},
    // RISCV_PIDFD_OPEN,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::PIDFD_OPEN},
    // RISCV_CLONE3,
    {SyscallAction::unimplemented, 2, AMD64_SYSCALL_ID::CLONE3},
    // RISCV_CLOSE_RANGE,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::CLOSE_RANGE},
    // RISCV_OPENAT2,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::OPENAT2},
    // RISCV_PIDFD_GETFD,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::PIDFD_GETFD},
    // RISCV_FACCESSAT2,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::FACCESSAT2},
    // RISCV_PROCESS_MADVISE,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::PROCESS_MADVISE},
    // RISCV_EPOLL_PWAIT2,
    {SyscallAction::handle, 6, AMD64_SYSCALL_ID::EPOLL_PWAIT2},
    // RISCV_MOUNT_SETATTR,
    {SyscallAction::passthrough, 5, AMD64_SYSCALL_ID::MOUNT_SETATTR},
    // RISCV_QUOTACTL_FD,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::QUOTACTL_FD},
    // RISCV_LANDLOCK_CREATE_RULESET,
    {SyscallAction::passthrough, 3, AMD64_SYSCALL_ID::LANDLOCK_CREATE_RULESET},
    // RISCV_LANDLOCK_ADD_RULE,
    {SyscallAction::passthrough, 4, AMD64_SYSCALL_ID::LANDLOCK_ADD_RULE},
    // RISCV_LANDLOCK_RESTRICT_SELF,
    {SyscallAction::passthrough, 2, AMD64_SYSCALL_ID::LANDLOCK_RESTRICT_SELF},
};

} // namespace helper
