#include "generator/x86_64/helper/rv64_syscalls.h"

// TODO: fix arg count for all non-passthrough syscalls so that the lifter can use them
const SyscallInfo rv64_syscall_table[RISCV_SYSCALL_ID_MAX + 1] = {
    // RISCV_IO_SETUP
    {SyscallAction::unimplemented, 0, AMD64_SYSCALL_ID_INVALID},
    // RISCV_IO_DESTROY
    {SyscallAction::unimplemented, 0, AMD64_SYSCALL_ID_INVALID},
    // RISCV_IO_SUBMIT
    {SyscallAction::unimplemented, 0, AMD64_SYSCALL_ID_INVALID},
    // RISCV_IO_CANCEL
    {SyscallAction::unimplemented, 0, AMD64_SYSCALL_ID_INVALID},
    // RISCV_IO_GET_EVENTS
    {SyscallAction::unimplemented, 0, AMD64_SYSCALL_ID_INVALID},
    // RISCV_SETXATTR = 5,
    {SyscallAction::passthrough, 5, AMD64_SETXATTR},
    // RISCV_LSETXATTR = 6,
    {SyscallAction::passthrough, 5, AMD64_LSETXATTR},
    // RISCV_FSETXATTR = 7,
    {SyscallAction::passthrough, 5, AMD64_FSETXATTR},
    // RISCV_GETXATTR = 8,
    {SyscallAction::passthrough, 4, AMD64_GETXATTR},
    // RISCV_LGETXATTR = 9,
    {SyscallAction::passthrough, 4, AMD64_LGETXATTR},
    // RISCV_FGETXATTR = 10,
    {SyscallAction::passthrough, 4, AMD64_FGETXATTR},
    // RISCV_LISTXATTR = 11,
    {SyscallAction::passthrough, 3, AMD64_LISTXATTR},
    // RISCV_LLISTXATTR = 12,
    {SyscallAction::passthrough, 3, AMD64_LLISTXATTR},
    // RISCV_FLISTXATTR = 13,
    {SyscallAction::passthrough, 3, AMD64_FLISTXATTR},
    // RISCV_REMOVEXATTR = 14,
    {SyscallAction::passthrough, 3, AMD64_REMOVEXATTR},
    // RISCV_LREMOVEXATTR = 15,
    {SyscallAction::passthrough, 3, AMD64_LREMOVEXATTR},
    // RISCV_FREMOVEXATTR = 16,
    {SyscallAction::passthrough, 3, AMD64_FREMOVEXATTR},
    // RISCV_GETCWD = 17,
    {SyscallAction::passthrough, 2, AMD64_GETCWD},
    // RISCV_LOOKUP_DCOOKIE = 18,
    {SyscallAction::passthrough, 3, AMD64_LOOKUP_DCOOKIE},
    // RISCV_EVENTFD2 = 19,
    {SyscallAction::passthrough, 2, AMD64_EVENTFD2},
    // RISCV_EPOLL_CREATE1 = 20,
    {SyscallAction::passthrough, 1, AMD64_EPOLL_CREATE1},
    // RISCV_EPOLL_CTL = 21,
    {SyscallAction::handle, 4, AMD64_EPOLL_CTL},
    // RISCV_EPOLL_PWAIT = 22,
    {SyscallAction::handle, 6, AMD64_EPOLL_PWAIT},
    // RISCV_DUP = 23,
    {SyscallAction::passthrough, 1, AMD64_DUP},
    // RISCV_DUP3 = 24,
    {SyscallAction::passthrough, 3, AMD64_DUP3},
    // RISCV_FCNTL = 25,
    {SyscallAction::passthrough, 3, AMD64_FCNTL},
    // RISCV_INOTIFY_INIT1 = 26,
    {SyscallAction::passthrough, 1, AMD64_INOTIFY_INIT1},
    // RISCV_INOTIFY_ADD_WATCH = 27,
    {SyscallAction::passthrough, 3, AMD64_INOTIFY_ADD_WATCH},
    // RISCV_INOTIFY_RM_WATCH = 28,
    {SyscallAction::passthrough, 2, AMD64_INOTIFY_RM_WATCH},
    // RISCV_IOCTL = 29,
    {SyscallAction::passthrough, 3, AMD64_IOCTL},
    // RISCV_IOPRIO_SET = 30,
    {SyscallAction::passthrough, 3, AMD64_IOPRIO_SET},
    // RISCV_IOPRIO_GET = 31,
    {SyscallAction::passthrough, 2, AMD64_IOPRIO_GET},
    // RISCV_FLOCK = 32,
    {SyscallAction::passthrough, 2, AMD64_FLOCK},
    // RISCV_MKNODAT = 33,
    {SyscallAction::passthrough, 4, AMD64_MKNODAT},
    // RISCV_MKDIRAT = 34,
    {SyscallAction::passthrough, 3, AMD64_MKDIRAT},
    // RISCV_UNLINKAT = 35,
    {SyscallAction::passthrough, 3, AMD64_UNLINKAT},
    // RISCV_SYMLINKAT = 36,
    {SyscallAction::passthrough, 3, AMD64_SYMLINKAT},
    // RISCV_LINKAT = 37,
    {SyscallAction::passthrough, 5, AMD64_LINKAT},
    // // 38 is skipped
    {SyscallAction::unimplemented, 0, AMD64_SYSCALL_ID_INVALID},
    // RISCV_UMOUNT2 = 39,
    {SyscallAction::passthrough, 2, AMD64_UMOUNT2},
    // RISCV_MOUNT = 40,
    {SyscallAction::passthrough, 5, AMD64_MOUNT},
    // RISCV_PIVOT_ROOT = 41,
    {SyscallAction::passthrough, 2, AMD64_PIVOT_ROOT},
    // // nfsservectl, doesn't exist since linux 3.1
    {SyscallAction::unimplemented, 0, AMD64_SYSCALL_ID_INVALID},
    // RISCV_STATFS = 43,
    {SyscallAction::passthrough, 2, AMD64_STATFS},
    // RISCV_FSTATFS = 44,
    {SyscallAction::passthrough, 2, AMD64_FSTATFS},
    // RISCV_TRUNCATE = 45,
    {SyscallAction::passthrough, 2, AMD64_TRUNCATE},
    // RISCV_FTRUNCATE = 46,
    {SyscallAction::passthrough, 2, AMD64_FTRUNCATE},
    // RISCV_FALLOCATE = 47,
    {SyscallAction::passthrough, 4, AMD64_FALLOCATE},
    // RISCV_FACCESSAT = 48,
    {SyscallAction::passthrough, 3, AMD64_FACCESSAT},
    // RISCV_CHDIR = 49,
    {SyscallAction::passthrough, 1, AMD64_CHDIR},
    // RISCV_FCHDIR = 50,
    {SyscallAction::passthrough, 1, AMD64_FCHDIR},
    // RISCV_CHROOT = 51,
    {SyscallAction::passthrough, 1, AMD64_CHROOT},
    // RISCV_FCHMOD = 52,
    {SyscallAction::passthrough, 2, AMD64_FCHMOD},
    // RISCV_FCHMODAT = 53,
    {SyscallAction::passthrough, 2, AMD64_FCHMODAT},
    // RISCV_FCHOWNAT = 54,
    {SyscallAction::passthrough, 5, AMD64_FCHOWNAT},
    // RISCV_FCHOWN = 55,
    {SyscallAction::passthrough, 3, AMD64_FCHOWN},
    // RISCV_OPENAT = 56,
    {SyscallAction::passthrough, 3, AMD64_OPENAT},
    // RISCV_CLOSE = 57,
    {SyscallAction::passthrough, 1, AMD64_CLOSE},
    // RISCV_VHANGUP = 58,
    {SyscallAction::passthrough, 0, AMD64_VHANGUP},
    // RISCV_PIPE2 = 59,
    {SyscallAction::passthrough, 2, AMD64_PIPE2},
    // RISCV_QUOTACTL = 60,
    {SyscallAction::passthrough, 4, AMD64_QUOTACTL},
    // RISCV_GETDENTS64 = 61,
    {SyscallAction::passthrough, 3, AMD64_GETDENTS64},
    // RISCV_LSEEK = 62,
    {SyscallAction::passthrough, 3, AMD64_LSEEK},
    // RISCV_READ = 63,
    {SyscallAction::passthrough, 3, AMD64_READ},
    // RISCV_WRITE = 64,
    {SyscallAction::passthrough, 3, AMD64_WRITE},
    // RISCV_READV = 65,
    {SyscallAction::passthrough, 3, AMD64_READV},
    // RISCV_WRITEV = 66,
    {SyscallAction::passthrough, 3, AMD64_WRITEV},
    // RISCV_PREAD64 = 67,
    {SyscallAction::passthrough, 4, AMD64_PREAD64},
    // RISCV_PWRITE64 = 68,
    {SyscallAction::passthrough, 4, AMD64_PWRITE64},
    // RISCV_PREADV = 69, TODO: the fourth arg is one 64bit but is split into high and low part on x64, check if its the same on riscv
    {SyscallAction::passthrough, 5, AMD64_PREADV},
    // RISCV_PWRITEV = 70, same as above
    {SyscallAction::passthrough, 5, AMD64_PWRITEV},
    // RISCV_SENDFILE = 71,
    {SyscallAction::passthrough, 4, AMD64_SENDFILE},
    // RISCV_PSELECT6 = 72,
    {SyscallAction::passthrough, 6, AMD64_PSELECT6},
    // RISCV_PPOLL = 73,
    {SyscallAction::passthrough, 5, AMD64_PPOLL},
    // RISCV_SIGNALFD4 = 74,
    {SyscallAction::passthrough, 4, AMD64_SIGNALFD4},
    // RISCV_VMSPLICE = 75,
    {SyscallAction::passthrough, 4, AMD64_VMSPLICE},
    // RISCV_SPLICE = 76,
    {SyscallAction::passthrough, 6, AMD64_SPLICE},
    // RISCV_TEE = 77,
    {SyscallAction::passthrough, 4, AMD64_TEE},
    // RISCV_READ_LINK_AT = 78,
    {SyscallAction::passthrough, 4, AMD64_READ_LINK_AT},
    // RISCV_FSTATAT = 79,
    {SyscallAction::handle, 4, AMD64_NEWFSTATAT},
    // RISCV_FSTAT = 80,
    {SyscallAction::handle, 2, AMD64_FSTAT},
    // RISCV_SYNC = 81,
    {SyscallAction::passthrough, 0, AMD64_SYNC},
    // RISCV_FSYNC = 82,
    {SyscallAction::passthrough, 1, AMD64_FSYNC},
    // RISCV_FDATASYNC = 83,
    {SyscallAction::passthrough, 1, AMD64_FDATASYNC},
    // RISCV_SYNC_FILE_RANGE = 84,
    {SyscallAction::passthrough, 4, AMD64_SYNC_FILE_RANGE},
    // RISCV_TIMERFD_CREATE = 85,
    {SyscallAction::passthrough, 2, AMD64_TIMERFD_CREATE},
    // RISCV_TIMERFD_SETTIME = 86,
    {SyscallAction::passthrough, 4, AMD64_TIMERFD_SETTIME},
    // RISCV_TIMERFD_GETTIME = 87,
    {SyscallAction::passthrough, 2, AMD64_TIMERFD_GETTIME},
    // RISCV_UTIME_NS_AT = 88,
    {SyscallAction::passthrough, 4, AMD64_UTIME_NS_AT},
    // RISCV_ACCT = 89,
    {SyscallAction::passthrough, 1, AMD64_ACCT},
    // RISCV_CAPGET = 90,
    {SyscallAction::passthrough, 2, AMD64_CAPGET},
    // RISCV_CAPSET = 91,
    {SyscallAction::passthrough, 2, AMD64_CAPSET},
    // RISCV_PERSONALITY = 92,
    {SyscallAction::passthrough, 1, AMD64_PERSONALITY},
    // RISCV_EXIT = 93,
    {SyscallAction::passthrough, 1, AMD64_EXIT},
    // RISCV_EXIT_GROUP = 94,
    {SyscallAction::passthrough, 1, AMD64_EXIT_GROUP},
    // RISCV_WAITID = 95,
    {SyscallAction::passthrough, 5, AMD64_WAITID},
    // RISCV_SET_TID_ADDR = 96,
    {SyscallAction::passthrough, 1, AMD64_SET_TID_ADDR},
    // RISCV_UNSHARE = 97,
    {SyscallAction::passthrough, 1, AMD64_UNSHARE},
    // RISCV_FUTEX = 98,
    {SyscallAction::passthrough, 6, AMD64_FUTEX},
    // RISCV_SET_ROBUST_LIST = 99,
    {SyscallAction::passthrough, 2, AMD64_SET_ROBUST_LIST},
    // RISCV_GET_ROBUST_LIST = 100,
    {SyscallAction::passthrough, 3, AMD64_GET_ROBUST_LIST},
    // RISCV_NANOSLEEP = 101,
    {SyscallAction::passthrough, 2, AMD64_NANOSLEEP},
    // RISCV_GETITIMER = 102,
    {SyscallAction::passthrough, 2, AMD64_GETITIMER},
    // RISCV_SETITIMER = 103,
    {SyscallAction::passthrough, 3, AMD64_SETITIMER},
    // RISCV_KEXEC_LOAD = 104,
    {SyscallAction::unimplemented, 0, AMD64_KEXEC_LOAD},
    // RISCV_INIT_MODULE = 105,
    {SyscallAction::unimplemented, 0, AMD64_INIT_MODULE},
    // RISCV_DELETE_MODULE = 106,
    {SyscallAction::unimplemented, 0, AMD64_DELETE_MODULE},
    // RISCV_TIMER_CREATE = 107, timer functions need signal support
    {SyscallAction::unimplemented, 0, AMD64_TIMER_CREATE},
    // RISCV_TIMER_GETTIME = 108,
    {SyscallAction::unimplemented, 0, AMD64_TIMER_GETTIME},
    // RISCV_TIMER_GETOVERRUN = 109,
    {SyscallAction::unimplemented, 0, AMD64_TIMER_GETOVERRUN},
    // RISCV_TIMER_SETTIME = 110,
    {SyscallAction::unimplemented, 0, AMD64_TIMER_SETTIME},
    // RISCV_TIMER_DELETE = 111,
    {SyscallAction::unimplemented, 0, AMD64_TIMER_DELETE},
    // RISCV_CLOCK_SETTIME = 112,
    {SyscallAction::passthrough, 2, AMD64_CLOCK_SETTIME},
    // RISCV_CLOCK_GET_TIME = 113,
    {SyscallAction::passthrough, 2, AMD64_CLOCK_GET_TIME},
    // RISCV_CLOCK_GETRES = 114,
    {SyscallAction::passthrough, 2, AMD64_CLOCK_GETRES},
    // RISCV_CLOCK_NANOSLEEP = 115,
    {SyscallAction::passthrough, 4, AMD64_CLOCK_NANOSLEEP},
    // RISCV_SYSLOG = 116,
    {SyscallAction::passthrough, 3, AMD64_SYSLOG},
    // RISCV_PTRACE = 117, deals with arch-specific data
    {SyscallAction::unimplemented, 0, AMD64_PTRACE},
    // RISCV_SCHED_SETPARAM = 118, riscv struct is bigger with padding bytes
    {SyscallAction::passthrough, 2, AMD64_SCHED_SETPARAM},
    // RISCV_SCHED_SETSCHEDULER = 119,
    {SyscallAction::passthrough, 3, AMD64_SCHED_SETSCHEDULER},
    // RISCV_SCHED_GETSCHEDULER = 120,
    {SyscallAction::passthrough, 1, AMD64_SCHED_GETSCHEDULER},
    // RISCV_SCHED_GETPARAM = 121,
    {SyscallAction::passthrough, 2, AMD64_SCHED_GETPARAM},
    // RISCV_SCHED_SETAFFINITY = 122,
    {SyscallAction::passthrough, 3, AMD64_SCHED_SETAFFINITY},
    // RISCV_SCHED_GETAFFINITY = 123,
    {SyscallAction::passthrough, 3, AMD64_SCHED_GETAFFINITY},
    // RISCV_SCHED_YIELD = 124,
    {SyscallAction::passthrough, 0, AMD64_SCHED_YIELD},
    // RISCV_SCHED_GET_PRIORITY_MAX = 125,
    {SyscallAction::passthrough, 1, AMD64_SCHED_GET_PRIORITY_MAX},
    // RISCV_SCHED_GET_PRIORITY_MIN = 126,
    {SyscallAction::passthrough, 1, AMD64_SCHED_GET_PRIORITY_MIN},
    // RISCV_SCHED_RR_GET_INTERVAL = 127,
    {SyscallAction::passthrough, 2, AMD64_SCHED_RR_GET_INTERVAL},
    // RISCV_RESTART_SYSCALL = 128,
    {SyscallAction::passthrough, 0, AMD64_RESTART_SYSCALL},
    // RISCV_KILL = 129,
    {SyscallAction::passthrough, 2, AMD64_KILL},
    // RISCV_TKILL = 130,
    {SyscallAction::passthrough, 2, AMD64_TKILL},
    // RISCV_TGKILL = 131,
    {SyscallAction::passthrough, 3, AMD64_TGKILL},
    // RISCV_SIGALTSTACK = 132,
    {SyscallAction::succeed, 0, AMD64_SIGALTSTACK},
    // RISCV_RT_SIGSUSPEND = 133, cant emulate in a meaningful way
    {SyscallAction::unimplemented, 0, AMD64_RT_SIGSUSPEND},
    // RISCV_RT_SIGACTION = 134,
    {SyscallAction::succeed, 0, AMD64_RT_SIGACTION},
    // RISCV_RT_SIGPROCMASK = 135,
    {SyscallAction::succeed, 0, AMD64_RT_SIGPROCMASK},
    // RISCV_RT_SIGPENDING = 136,
    {SyscallAction::passthrough, 1, AMD64_RT_SIGPENDING},
    // RISCV_RT_SIGTIMEDWAIT = 137,
    {SyscallAction::unimplemented, 0, AMD64_RT_SIGTIMEDWAIT},
    // RISCV_RT_SIGQUEUEINFO = 138,
    {SyscallAction::unimplemented, 0, AMD64_RT_SIGQUEUEINFO},
    // RISCV_RT_SIGRETURN = 139,
    {SyscallAction::unimplemented, 0, AMD64_RT_SIGRETURN},
    // RISCV_SETPRIORITY = 140,
    {SyscallAction::passthrough, 3, AMD64_SETPRIORITY},
    // RISCV_GETPRIORITY = 141,
    {SyscallAction::passthrough, 2, AMD64_GETPRIORITY},
    // RISCV_REBOOT = 142,
    {SyscallAction::passthrough, 4, AMD64_REBOOT},
    // RISCV_SETREGID = 143,
    {SyscallAction::passthrough, 2, AMD64_SETREGID},
    // RISCV_SETGID = 144,
    {SyscallAction::passthrough, 1, AMD64_SETGID},
    // RISCV_SETREUID = 145,
    {SyscallAction::passthrough, 2, AMD64_SETREUID},
    // RISCV_SETUID = 146,
    {SyscallAction::passthrough, 1, AMD64_SETUID},
    // RISCV_SETRESUID = 147,
    {SyscallAction::passthrough, 3, AMD64_SETRESUID},
    // RISCV_GETRESUID = 148,
    {SyscallAction::passthrough, 3, AMD64_GETRESUID},
    // RISCV_SETRESGID = 149,
    {SyscallAction::passthrough, 3, AMD64_SETRESGID},
    // RISCV_GETRESGID = 150,
    {SyscallAction::passthrough, 3, AMD64_GETRESGID},
    // RISCV_SETFSUID = 151,
    {SyscallAction::passthrough, 1, AMD64_SETFSUID},
    // RISCV_SETFSGID = 152,
    {SyscallAction::passthrough, 1, AMD64_SETFSGID},
    // RISCV_TIMES = 153,
    {SyscallAction::passthrough, 1, AMD64_TIMES},
    // RISCV_SETPGID = 154,
    {SyscallAction::passthrough, 2, AMD64_SETPGID},
    // RISCV_GETPGID = 155,
    {SyscallAction::passthrough, 1, AMD64_GETPGID},
    // RISCV_GETSID = 156,
    {SyscallAction::passthrough, 1, AMD64_GETSID},
    // RISCV_SETSID = 157,
    {SyscallAction::passthrough, 0, AMD64_SETSID},
    // RISCV_GETGROUPS = 158,
    {SyscallAction::passthrough, 2, AMD64_GETGROUPS},
    // RISCV_SETGROUPS = 159,
    {SyscallAction::passthrough, 2, AMD64_SETGROUPS},
    // RISCV_UNAME = 160,
    {SyscallAction::passthrough, 1, AMD64_UNAME},
    // RISCV_SETHOSTNAME = 161,
    {SyscallAction::passthrough, 2, AMD64_SETHOSTNAME},
    // RISCV_SETDOMAINNAME = 162,
    {SyscallAction::passthrough, 2, AMD64_SETDOMAINNAME},
    // RISCV_GETRLIMIT = 163,
    {SyscallAction::passthrough, 2, AMD64_GETRLIMIT},
    // RISCV_SETRLIMIT,
    {SyscallAction::passthrough, 2, AMD64_SETRLIMIT},
    // RISCV_GETRUSAGE,
    {SyscallAction::passthrough, 2, AMD64_GETRUSAGE},
    // RISCV_UMASK,
    {SyscallAction::passthrough, 1, AMD64_UMASK},
    // RISCV_PRCTL,
    {SyscallAction::passthrough, 5, AMD64_PRCTL},
    // RISCV_GETCPU,
    {SyscallAction::passthrough, 2, AMD64_GETCPU},
    // RISCV_GETTIMEOFDAY,
    {SyscallAction::passthrough, 2, AMD64_GETTIMEOFDAY},
    // RISCV_SETTIMEOFDAY,
    {SyscallAction::passthrough, 2, AMD64_SETTIMEOFDAY},
    // RISCV_ADJTIMEEX,
    {SyscallAction::passthrough, 1, AMD64_ADJTIMEX},
    // RISCV_GETPID,
    {SyscallAction::passthrough, 0, AMD64_GETPID},
    // RISCV_GETPPID,
    {SyscallAction::passthrough, 0, AMD64_GETPPID},
    // RISCV_GETUID,
    {SyscallAction::passthrough, 0, AMD64_GETUID},
    // RISCV_GETEUID,
    {SyscallAction::passthrough, 0, AMD64_GETEUID},
    // RISCV_GETGID,
    {SyscallAction::passthrough, 0, AMD64_GETGID},
    // RISCV_GETEGID,
    {SyscallAction::passthrough, 0, AMD64_GETEGID},
    // RISCV_GETTID,
    {SyscallAction::passthrough, 0, AMD64_GETTID},
    // RISCV_SYSINFO,
    {SyscallAction::passthrough, 1, AMD64_SYSINFO},
    // RISCV_MQ_OPEN,
    {SyscallAction::passthrough, 4, AMD64_MQ_OPEN},
    // RISCV_MQ_UNLINK,
    {SyscallAction::passthrough, 1, AMD64_MQ_UNLINK},
    // RISCV_MQ_TIMEDSEND,
    {SyscallAction::passthrough, 5, AMD64_MQ_TIMEDSEND},
    // RISCV_MQ_TIMEDRECEIVE,
    {SyscallAction::passthrough, 5, AMD64_MQ_TIMEDRECEIVE},
    // RISCV_MQ_NOTIFY,
    {SyscallAction::passthrough, 2, AMD64_MQ_NOTIFY},
    // RISCV_MQ_GETSETATTR,
    {SyscallAction::passthrough, 3, AMD64_MQ_GETSETATTR},
    // RISCV_MSGGET,
    {SyscallAction::passthrough, 2, AMD64_MSGGET},
    // RISCV_MSGCTL,
    {SyscallAction::passthrough, 3, AMD64_MSGCTL},
    // RISCV_MSGRCV,
    {SyscallAction::passthrough, 5, AMD64_MSGRCV},
    // RISCV_MSGSND,
    {SyscallAction::passthrough, 4, AMD64_MSGSND},
    // RISCV_SEMGET,
    {SyscallAction::passthrough, 3, AMD64_SEMGET},
    // RISCV_SEMCTL,
    {SyscallAction::passthrough, 4, AMD64_SEMCTL},
    // RISCV_SEMTIMEDOP,
    {SyscallAction::passthrough, 4, AMD64_SEMTIMEDOP},
    // RISCV_SEMOP,
    {SyscallAction::passthrough, 3, AMD64_SEMOP},
    // RISCV_SHMGET,
    {SyscallAction::passthrough, 3, AMD64_SHMGET},
    // RISCV_SHMCTL,
    {SyscallAction::passthrough, 3, AMD64_SHMCTL},
    // RISCV_SHMAT,
    {SyscallAction::passthrough, 3, AMD64_SHMAT},
    // RISCV_SHMDT,
    {SyscallAction::passthrough, 1, AMD64_SHMDT},
    // RISCV_SOCKET, socket stuff structs need to be checked
    {SyscallAction::unimplemented, 0, AMD64_SOCKET},
    // RISCV_SOCKETPAIR,
    {SyscallAction::unimplemented, 0, AMD64_SOCKETPAIR},
    // RISCV_BIND,
    {SyscallAction::unimplemented, 0, AMD64_BIND},
    // RISCV_LISTEN,
    {SyscallAction::unimplemented, 0, AMD64_LISTEN},
    // RISCV_ACCEPT,
    {SyscallAction::unimplemented, 0, AMD64_ACCEPT},
    // RISCV_CONNECT,
    {SyscallAction::unimplemented, 0, AMD64_CONNECT},
    // RISCV_GETSOCKETNAME,
    {SyscallAction::unimplemented, 0, AMD64_GETSOCKETNAME},
    // RISCV_GETPEERNAME,
    {SyscallAction::unimplemented, 0, AMD64_GETPEERNAME},
    // RISCV_SENDTO,
    {SyscallAction::unimplemented, 0, AMD64_SENDTO},
    // RISCV_RECVFROM,
    {SyscallAction::unimplemented, 0, AMD64_RECVFROM},
    // RISCV_SETSOCKOPT,
    {SyscallAction::unimplemented, 0, AMD64_SETSOCKOPT},
    // RISCV_GETSOCKOPT,
    {SyscallAction::unimplemented, 0, AMD64_GET_SOCKOPT},
    // RISCV_SHUTDOWN,
    {SyscallAction::unimplemented, 0, AMD64_SHUTDOWN},
    // RISCV_SENDMSG,
    {SyscallAction::unimplemented, 0, AMD64_SENDMSG},
    // RISCV_RECVMSG,
    {SyscallAction::unimplemented, 0, AMD64_RECVMSG},
    // RISCV_READAHEAD,
    {SyscallAction::passthrough, 3, AMD64_READAHEAD},
    // RISCV_BRK = 214,
    {SyscallAction::passthrough, 1, AMD64_BRK},
    // RISCV_MUNMAP = 215,
    {SyscallAction::passthrough, 2, AMD64_MUNMAP},
    // RISCV_MREMAP,
    {SyscallAction::passthrough, 5, AMD64_MREMAP},
    // RISCV_ADD_KEY,
    {SyscallAction::passthrough, 5, AMD64_ADD_KEY},
    // RISCV_REQUEST_KEY,
    {SyscallAction::passthrough, 4, AMD64_REQUEST_KEY},
    // RISCV_KEYCTL,
    {SyscallAction::passthrough, 5, AMD64_KEYCTL},
    // RISCV_CLONE,
    {SyscallAction::unimplemented, 0, AMD64_CLONE},
    // RISCV_EXECVE,
    {SyscallAction::unimplemented, 0, AMD64_EXECVE},
    // RISCV_MMAP = 222,
    {SyscallAction::passthrough, 6, AMD64_MMAP},
    // RISCV_FADVISE64,
    {SyscallAction::passthrough, 4, AMD64_FADVISE64},
    // RISCV_SWAPON,
    {SyscallAction::passthrough, 2, AMD64_SWAPON},
    // RISCV_SWAPOFF,
    {SyscallAction::passthrough, 1, AMD64_SWAPOFF},
    // RISCV_MPROTECT = 226,
    {SyscallAction::passthrough, 3, AMD64_MPROTECT},
    // RISCV_MSYNC,
    {SyscallAction::passthrough, 3, AMD64_MSYNC},
    // RISCV_MLOCK,
    {SyscallAction::passthrough, 2, AMD64_MLOCK},
    // RISCV_MUNLOCK,
    {SyscallAction::passthrough, 2, AMD64_MUNLOCK},
    // RISCV_MLOCKALL,
    {SyscallAction::passthrough, 1, AMD64_MLOCKALL},
    // RISCV_MUNLOCKALL,
    {SyscallAction::passthrough, 0, AMD64_MUNLOCKALL},
    // RISCV_MINCORE,
    {SyscallAction::passthrough, 3, AMD64_MINCORE},
    // RISCV_MADVISE = 233,
    {SyscallAction::passthrough, 3, AMD64_MADVISE},
    // RISCV_REMAP_FILE_PAGES,
    {SyscallAction::passthrough, 5, AMD64_REMAP_FILE_PAGES},
    // RISCV_MBIND,
    {SyscallAction::passthrough, 6, AMD64_MBIND},
    // RISCV_GET_MEMPOLICY,
    {SyscallAction::passthrough, 5, AMD64_GET_MEMPOLICY},
    // RISCV_SET_MEMPOLICY,
    {SyscallAction::passthrough, 3, AMD64_SET_MEMPOLICY},
    // RISCV_MIGRATE_PAGES,
    {SyscallAction::passthrough, 4, AMD64_MIGRATE_PAGES},
    // RISCV_MOVE_PAGES,
    {SyscallAction::passthrough, 6, AMD64_MOVE_PAGES},
    // RISCV_RT_TGSIGQUEUEINFO,
    {SyscallAction::unimplemented, 0, AMD64_RT_TGSIGQUEUEINFO},
    // RISCV_PERF_EVENT_OPEN,
    {SyscallAction::unimplemented, 0, AMD64_PERF_EVENT_OPEN},
    // RISCV_ACCEPT4,
    {SyscallAction::unimplemented, 0, AMD64_ACCEPT4},
    // RISCV_RECVMMSG,
    {SyscallAction::unimplemented, 0, AMD64_RECVMMSG},
    // RISCV_FLUSH_ICACHE,
    {SyscallAction::succeed, 0, AMD64_SYSCALL_ID_INVALID},
    // RISCV_WAIT4,
    {SyscallAction::passthrough, 4, AMD64_WAIT4},
    // RISCV_PRLIMIT64,
    {SyscallAction::passthrough, 4, AMD64_PRLIMIT64},
    // RISCV_FANOTIFY_INIT,
    {SyscallAction::passthrough, 2, AMD64_FANOTIFY_INIT},
    // RISCV_FANOTIFY_MARK,
    {SyscallAction::passthrough, 5, AMD64_FANOTIFY_MARK},
    // RISCV_NAME_TO_HANDLE_AT,
    {SyscallAction::passthrough, 5, AMD64_NAME_TO_HANDLE_AT},
    // RISCV_OPEN_BY_HANDLE_AT,
    {SyscallAction::passthrough, 3, AMD64_OPEN_BY_HANDLE_AT},
    // RISCV_CLOCK_ADJTIME,
    {SyscallAction::passthrough, 2, AMD64_CLOCK_ADJTIME},
    // RISCV_SYNCFS,
    {SyscallAction::passthrough, 1, AMD64_SYNCFS},
    // RISCV_SETNS,
    {SyscallAction::passthrough, 2, AMD64_SETNS},
    // RISCV_SENDMMSG,
    {SyscallAction::unimplemented, 0, AMD64_SENDMMSG},
    // RISCV_PROCESS_VM_READV,
    {SyscallAction::passthrough, 6, AMD64_PROCESS_VM_READV},
    // RISCV_PROCESS_VM_WRITEV,
    {SyscallAction::passthrough, 6, AMD64_PROCESS_VM_WRITEV},
    // RISCV_KCMP,
    {SyscallAction::passthrough, 5, AMD64_KCMP},
    // RISCV_FINIT_MODULE,
    {SyscallAction::unimplemented, 0, AMD64_FINIT_MODULE},
    // RISCV_SCHED_SETATTR,
    {SyscallAction::passthrough, 3, AMD64_SCHED_SETATTR},
    // RISCV_SCHED_GETATTR,
    {SyscallAction::passthrough, 4, AMD64_SCHED_GETATTR},
    // RISCV_RENAMEAT2,
    {SyscallAction::passthrough, 5, AMD64_RENAMEAT2},
    // RISCV_SECCOMP, arch-specific stuff?
    {SyscallAction::passthrough, 3, AMD64_SECCOMP},
    // RISCV_GETRANDOM,
    {SyscallAction::passthrough, 3, AMD64_GETRANDOM},
    // RISCV_MEMFDCREATE,
    {SyscallAction::passthrough, 2, AMD64_MEMFD_CREATE},
    // RISCV_BPF,
    {SyscallAction::passthrough, 3, AMD64_BPF},
    // RISCV_EXECVEAT,
    {SyscallAction::unimplemented, 0, AMD64_EXECVEAT},
    // RISCV_USERFAULTFD,
    {SyscallAction::passthrough, 1, AMD64_USERFAULTFD},
    // RISCV_MEMBARRIER,
    {SyscallAction::passthrough, 3, AMD64_MEMBARRIER},
    // RISCV_MLOCK2,
    {SyscallAction::passthrough, 3, AMD64_MLOCK2},
    // RISCV_COPY_FILE_RANGE,
    {SyscallAction::passthrough, 6, AMD64_COPY_FILE_RANGE},
    // RISCV_PREADV2,
    {SyscallAction::passthrough, 5, AMD64_PREADV2},
    // RISCV_PWRITEV2,
    {SyscallAction::passthrough, 5, AMD64_PWRITEV2},
    // RISCV_PKEY_MPROTECT,
    {SyscallAction::passthrough, 4, AMD64_PKEY_MPROTECT},
    // RISCV_PKEY_ALLOC,
    {SyscallAction::passthrough, 2, AMD64_PKEY_ALLOC},
    // RISCV_PKEY_FREE,
    {SyscallAction::passthrough, 1, AMD64_PKEY_FREE},
    // RISCV_STATX,
    {SyscallAction::passthrough, 5, AMD64_STATX},
    // RISCV_IO_PGETEVENTS,
    {SyscallAction::unimplemented, 0, AMD64_IO_PGETEVENTS},
    // RISCV_RSEQ,
    {SyscallAction::unimplemented, 0, AMD64_RSEQ},
    // RISCV_KEXEC_FILE_LOAD = 294,
    {SyscallAction::unimplemented, 0, AMD64_KEXEC_FILE_LOAD},
    // 424 - 295 = 129 zero entries
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    // RISCV_PIDFD_SEND_SIGNAL = 424,
    {SyscallAction::passthrough, 4, AMD64_PIDFD_SEND_SIGNAL},
    // RISCV_IO_URING_SETUP, not sure about the structs
    {SyscallAction::unimplemented, 0, AMD64_IO_URING_SETUP},
    // RISCV_IO_URING_ENTER,
    {SyscallAction::unimplemented, 0, AMD64_IO_URING_ENTER},
    // RISCV_IO_URING_REGISTER,
    {SyscallAction::unimplemented, 0, AMD64_IO_URING_REGISTER},
    // RISCV_OPEN_TREE,
    {SyscallAction::passthrough, 3, AMD64_OPEN_TREE},
    // RISCV_MOVE_MOUNT,
    {SyscallAction::passthrough, 5, AMD64_MOVE_MOUNT},
    // RISCV_FSOPEN,
    {SyscallAction::passthrough, 2, AMD64_FSOPEN},
    // RISCV_FSCONFIG,
    {SyscallAction::passthrough, 5, AMD64_FSCONFIG},
    // RISCV_FSMOUNT,
    {SyscallAction::passthrough, 3, AMD64_FSMOUNT},
    // RISCV_FSPICK,
    {SyscallAction::passthrough, 3, AMD64_FSPICK},
    // RISCV_PIDFD_OPEN,
    {SyscallAction::passthrough, 2, AMD64_PIDFD_OPEN},
    // RISCV_CLONE3,
    {SyscallAction::unimplemented, 0, AMD64_CLONE3},
    // RISCV_CLOSE_RANGE,
    {SyscallAction::passthrough, 3, AMD64_CLOSE_RANGE},
    // RISCV_OPENAT2,
    {SyscallAction::passthrough, 4, AMD64_OPENAT2},
    // RISCV_PIDFD_GETFD,
    {SyscallAction::passthrough, 3, AMD64_PIDFD_GETFD},
    // RISCV_FACCESSAT2,
    {SyscallAction::passthrough, 4, AMD64_FACCESSAT2},
    // RISCV_PROCESS_MADVISE,
    {SyscallAction::passthrough, 5, AMD64_PROCESS_MADVISE},
    // RISCV_EPOLL_PWAIT2,
    {SyscallAction::handle, 6, AMD64_EPOLL_PWAIT2},
    // RISCV_MOUNT_SETATTR,
    {SyscallAction::passthrough, 5, AMD64_MOUNT_SETATTR},
    // RISCV_QUOTACTL_FD,
    {SyscallAction::passthrough, 4, AMD64_QUOTACTL_FD},
    // RISCV_LANDLOCK_CREATE_RULESET,
    {SyscallAction::passthrough, 3, AMD64_LANDLOCK_CREATE_RULESET},
    // RISCV_LANDLOCK_ADD_RULE,
    {SyscallAction::passthrough, 4, AMD64_LANDLOCK_ADD_RULE},
    // RISCV_LANDLOCK_RESTRICT_SELF,
    {SyscallAction::passthrough, 2, AMD64_LANDLOCK_RESTRICT_SELF},
};
